# Convolution example using tf.nn.conv2d

In [15]:
import tensorflow as tf

In [16]:
i = tf.constant([
    [4, 3, 1, 0],
    [2, 1, 0, 1],
    [1, 2, 4, 1],
    [3, 1, 0, 2]],
    dtype=tf.float32,
    name='input')

In [17]:
k = tf.constant([
    [1, 0, 1],
    [2, 1, 0],
    [0, 0, 10]],
    dtype='float32',
    name='k')

In [18]:
image = tf.reshape(i, [1, 4, 4, 1], name='image')
kernel = tf.reshape(k, [3, 3, 1, 1], name='kernel')

In [19]:
res_with_no_padding = tf.squeeze(tf.nn.conv2d(image, kernel, [1, 1, 1, 1], padding='VALID', use_cudnn_on_gpu=True))

In [20]:
res_with_zero_padding = tf.squeeze(tf.nn.conv2d(image, kernel, [1, 1, 1, 1], padding='SAME', use_cudnn_on_gpu=True))

In [21]:
with tf.Session() as sess:
    print(sess.run(res_with_no_padding))
    print(sess.run(res_with_zero_padding))

[[50. 15.]
 [ 6. 30.]]
[[14. 11. 17.  2.]
 [25. 50. 15.  2.]
 [12.  6. 30.  9.]
 [ 5. 12.  5.  6.]]
